export const GET_EXPERIENCE_DATA = 'GET_EXPERIENCE_DATA';
export const GET_EXPERIENCE_DATA_SUCCESS = 'GET_EXPERIENCE_DATA_SUCCESS';
export const GET_EXPERIENCE_DATA_FAILURE = 'GET_EXPERIENCE_DATA_FAILURE';
