export const GET_CANCELLATION_POLICY_DATA = 'GET_CANCELLATION_POLICY_DATA';
export const GET_CANCELLATION_POLICY_DATA_SUCCESS = 'GET_CANCELLATION_POLICY_DATA_SUCCESS';
export const GET_CANCELLATION_POLICY_DATA_FAILURE = 'GET_CANCELLATION_POLICY_DATA_FAILURE';

export const CREATE_CANCELLATION_POLICY = 'CREATE_CANCELLATION_POLICY';
export const CREATE_CANCELLATION_POLICY_SUCCESS = 'CREATE_CANCELLATION_POLICY_SUCCESS';
export const CREATE_CANCELLATION_POLICY_FAILURE = 'CREATE_CANCELLATION_POLICY_FAILURE';

export const DELETE_CANCELLATION_POLICY = 'DELETE_CANCELLATION_POLICY';
export const DELETE_CANCELLATION_POLICY_SUCCESS = 'DELETE_CANCELLATION_POLICY_SUCCESS';
export const DELETE_CANCELLATION_POLICY_FAILURE = 'DELETE_CANCELLATION_POLICY_FAILURE';

export const UPDATE_CANCELLATION_POLICY = 'UPDATE_CANCELLATION_POLICY';
export const UPDATE_CANCELLATION_POLICY_SUCCESS = 'UPDATE_CANCELLATION_POLICY_SUCCESS';
export const UPDATE_CANCELLATION_POLICY_FAILURE = 'UPDATE_CANCELLATION_POLICY_FAILURE';

export const REORDER_CANCELLATION_POLICY = 'REORDER_CANCELLATION_POLICY';
export const REORDER_CANCELLATION_POLICY_SUCCESS = 'REORDER_CANCELLATION_POLICY_SUCCESS';
export const REORDER_CANCELLATION_POLICY_FAILURE = 'REORDER_CANCELLATION_POLICY_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
