export const GET_SUB_CATEGORY_DATA = 'GET_SUB_CATEGORY_DATA';
export const GET_SUB_CATEGORY_DATA_SUCCESS = 'GET_SUB_CATEGORY_DATA_SUCCESS';
export const GET_SUB_CATEGORY_DATA_FAILURE = 'GET_SUB_CATEGORY_DATA_FAILURE';

export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY';
export const CREATE_SUB_CATEGORY_SUCCESS = 'CREATE_SUB_CATEGORY_SUCCESS';
export const CREATE_SUB_CATEGORY_FAILURE = 'CREATE_SUB_CATEGORY_FAILURE';

export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY';
export const UPDATE_SUB_CATEGORY_SUCCESS = 'UPDATE_SUB_CATEGORY_SUCCESS';
export const UPDATE_SUB_CATEGORY_FAILURE = 'UPDATE_SUB_CATEGORY_FAILURE';

export const DELETE_SUB_CATEGORY = 'DELETE_SUB_CATEGORY';
export const DELETE_SUB_CATEGORY_SUCCESS = 'DELETE_SUB_CATEGORY_SUCCESS';
export const DELETE_SUB_CATEGORY_FAILURE = 'DELETE_SUB_CATEGORY_FAILURE';
