export const GET_SUB_CATEGORY_DATA = 'GET_SUB_CATEGORY_DATA';
export const GET_SUB_CATEGORY_DATA_SUCCESS = 'GET_SUB_CATEGORY_DATA_SUCCESS';
export const GET_SUB_CATEGORY_DATA_FAILURE = 'GET_SUB_CATEGORY_DATA_FAILURE';
