export const GET_IMAGE_DATA = 'GET_IMAGE_DATA';
export const GET_IMAGE_DATA_SUCCESS = 'GET_IMAGE_DATA_SUCCESS';
export const GET_IMAGE_DATA_FAILURE = 'GET_IMAGE_DATA_FAILURE';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILURE = 'DELETE_IMAGE_FAILURE';

export const DOWNLOAD_IMAGE = 'DOWNLOAD_IMAGE';
export const DOWNLOAD_IMAGE_SUCCESS = 'DOWNLOAD_IMAGE_SUCCESS';
export const DOWNLOAD_IMAGE_FAILURE = 'DOWNLOAD_IMAGE_FAILURE';

export const GET_IMAGE_METADATA = 'GET_IMAGE_METADATA';
export const GET_IMAGE_METADATA_SUCCESS = 'GET_IMAGE_METADATA_SUCCESS';
export const GET_IMAGE_METADATA_FAILURE = 'GET_IMAGE_METADATA_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
