export const GET_INCLUSION_DATA = 'GET_INCLUSION_DATA';
export const GET_INCLUSION_DATA_SUCCESS = 'GET_INCLUSION_DATA_SUCCESS';
export const GET_INCLUSION_DATA_FAILURE = 'GET_INCLUSION_DATA_FAILURE';

export const CREATE_INCLUSION = 'CREATE_INCLUSION';
export const CREATE_INCLUSION_SUCCESS = 'CREATE_INCLUSION_SUCCESS';
export const CREATE_INCLUSION_FAILURE = 'CREATE_INCLUSION_FAILURE';

export const DELETE_INCLUSION = 'DELETE_INCLUSION';
export const DELETE_INCLUSION_SUCCESS = 'DELETE_INCLUSION_SUCCESS';
export const DELETE_INCLUSION_FAILURE = 'DELETE_INCLUSION_FAILURE';

export const UPDATE_INCLUSION = 'UPDATE_INCLUSION';
export const UPDATE_INCLUSION_SUCCESS = 'UPDATE_INCLUSION_SUCCESS';
export const UPDATE_INCLUSION_FAILURE = 'UPDATE_INCLUSION_FAILURE';

export const REORDER_INCLUSION = 'REORDER_INCLUSION';
export const REORDER_INCLUSION_SUCCESS = 'REORDER_INCLUSION_SUCCESS';
export const REORDER_INCLUSION_FAILURE = 'REORDER_INCLUSION_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';
