export const GET_LOCATION_DATA = 'GET_LOCATION_DATA';
export const GET_LOCATION_DATA_SUCCESS = 'GET_LOCATION_DATA_SUCCESS';
export const GET_LOCATION_DATA_FAILURE = 'GET_LOCATION_DATA_FAILURE';

export const CREATE_LOCATION = 'CREATE_LOCATION';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_FAILURE = 'CREATE_LOCATION_FAILURE';

export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAILURE = 'DELETE_LOCATION_FAILURE';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAILURE = 'UPDATE_LOCATION_FAILURE';

export const REORDER_LOCATION = 'REORDER_LOCATION';
export const REORDER_LOCATION_SUCCESS = 'REORDER_LOCATION_SUCCESS';
export const REORDER_LOCATION_FAILURE = 'REORDER_LOCATION_FAILURE';

export const RESET_STATUS = 'RESET_STATUS';

export const GET_PINCODE_DATA = 'GET_PINCODE_DATA';
export const GET_PINCODE_DATA_SUCCESS = 'GET_PINCODE_DATA_SUCCESS';
export const GET_PINCODE_DATA_FAILURE = 'GET_PINCODE_DATA_FAILURE';

export const CREATE_PINCODE = 'CREATE_PINCODE';
export const CREATE_PINCODE_SUCCESS = 'CREATE_PINCODE_SUCCESS';
export const CREATE_PINCODE_FAILURE = 'CREATE_PINCODE_FAILURE';

export const DELETE_PINCODE = 'DELETE_PINCODE';
export const DELETE_PINCODE_SUCCESS = 'DELETE_PINCODE_SUCCESS';
export const DELETE_PINCODE_FAILURE = 'DELETE_PINCODE_FAILURE';

export const UPDATE_PINCODE = 'UPDATE_PINCODE';
export const UPDATE_PINCODE_SUCCESS = 'UPDATE_PINCODE_SUCCESS';
export const UPDATE_PINCODE_FAILURE = 'UPDATE_PINCODE_FAILURE';
